name: WASM

on:
  workflow_dispatch:

env:
  PRESET: debug::emscripten
  CMAKE_VERSION: 4.2.3
  NINJA_VERSION: 1.13.1

jobs:
  build:
    runs-on: ubuntu-24.04
    container: emscripten/emsdk:5.0.2

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Get CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: ${{env.CMAKE_VERSION}}
          ninjaVersion: ${{env.NINJA_VERSION}}
        
      - name: CMake Configuration
        env:
          EMSCRIPTEN_ROOT: /emsdk/upstream/emscripten
        run: cmake --preset=${{env.PRESET}}

      - name: CMake Build
        run: cmake --build --preset=${{env.PRESET}}
