name: macOS clang

on:
  workflow_dispatch:

env:
  PRESET: debug
  LLVM: 20
  CMAKE_VERSION: 4.2.3
  NINJA_VERSION: 1.13.1

jobs:
  build:
    runs-on: macos-26

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
          
      - name: CMake Configuration
        run: |
          cmake --preset=${{env.PRESET}}  \
            -DCMAKE_C_COMPILER=$(brew --prefix llvm@${{env.LLVM}})/bin/clang        \
            -DCMAKE_CXX_COMPILER=$(brew --prefix llvm@${{env.LLVM}})/bin/clang++    \
            -DCMAKE_PREFIX_PATH=$(brew --prefix llvm@${{env.LLVM}})                 \
            -DCMAKE_OSX_SYSROOT=macosx \
            -DCMAKE_CXX_COMPILER_ID_ARG1=-resource-dir=$(brew --prefix llvm@${{env.LLVM}})/lib/c++

      - name: CMake Build
        run: cmake --build --preset=${{env.PRESET}}
