name: Windows MSVC

on:
  workflow_dispatch:

env:
  PRESET: debug
  CMAKE_VERSION: 4.2.3
  NINJA_VERSION: 1.13.1

jobs:
  build:
    runs-on: windows-2025-vs2026

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup VS Environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          vsversion: 18

      - name: CMake Configuration
        run: cmake --preset=${{env.PRESET}}

      - name: CMake Build
        run: cmake --build --preset=${{env.PRESET}}
